MODEL_2D:
  TYPE: "UNetResNet34"
  DUAL_HEAD: True
  NUM_CLASSES: 6
MODEL_3D:
  TYPE: "SCN"
  DUAL_HEAD: True
  NUM_CLASSES: 6
DATASET_SOURCE:
  TYPE: "VirtualKITTISCN"
  TRAIN: ("train",)
  VirtualKITTISCN:
    preprocess_dir: '/data/xmw/xmuda-journal-dataset/virtual_kitti_preprocess_intensity/preprocess'
    virtual_kitti_dir: '/data/xmw/virtual_kitti'
DATASET_TARGET:
  TYPE: "SemanticKITTISCN"
  TRAIN: ("train",)
  VAL: ("test",)  # ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    preprocess_dir: '/data/xmw/xmuda-journal-dataset/semantic_kitti_preprocess_intensity1/preprocess'
    semantic_kitti_dir: '/data/xmw/semantic_kitti'
    merge_classes_style: "VirtualKITTI"
    pselab_paths: ("/data1/wuyao/code/BFtD-journal/output/vkitti_skitti/BFtD_uni/pselab_data/train.npy",)
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (48000, 56000)
  MAX_ITERATION: 60000
TRAIN:
  BATCH_SIZE: 4
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 4000
  CLASS_WEIGHTS: [1., 2.03402089, 1.20641905, 2.21588055, 2.59745666, 1.82057006]
  XMUDA:
    lambda_xm_src: 0.1
    lambda_xm_trg: 0.02
    lambda_cmkd: 0.01
    lambda_pl: 1.0
VAL:
  BATCH_SIZE: 1
  PERIOD: 4000

OUTPUT_DIR: "/data1/wuyao/code/BFtD-journal/output/vkitti_skitti/BFtD_uni_xDPL/"
